### ISSUE TITLE
Error decoding

### ISSUE THREAD

**Issue by patchthecode** [orlandos-nl/IkigaJSON#26]
```swift
return app.client.get("http://\(FROSTFLAKE_HOST):\(FROSTFLAKE_PORT)/id").flatMapThrowing { clientResponse in
    let response = try clientResponse.content.decode([UInt64].self)
    guard let id = response.first else { throw Abort(.badRequest)}
    return id
}
```

When trying to decode an array on Uint64, it throws Error.

Vapor log
```
[ INFO ] [Migrator] Starting prepare [database-id: psql, migration: App.GenerateChatMessages]
Generating sample chat messages
NIOCore/ByteBuffer-core.swift:382: Assertion failed
NIOCore/ByteBuffer-core.swift:382: Assertion failed
NIOCore/ByteBuffer-core.swift:382: Assertion failed
NIOCore/ByteBuffer-core.swift:382: Assertion failed
2022-11-20 11:59:45.400158-0500 Run[40437:4076049] NIOCore/ByteBuffer-core.swift:382: Assertion failed
2022-11-20 11:59:45.400161-0500 Run[40437:4076050] NIOCore/ByteBuffer-core.swift:382: Assertion failed
2022-11-20 11:59:45.400169-0500 Run[40437:4076053] NIOCore/ByteBuffer-core.swift:382: Assertion failed
2022-11-20 11:59:45.400179-0500 Run[40437:4076051] NIOCore/ByteBuffer-core.swift:382: Assertion failed
```

```
IkigaJSON/JSONDescription.swift:118: Assertion failed
NIOCore/ByteBuffer-core.swift:382: Assertion failed
IkigaJSON/JSONParser.swift:50: Assertion failed: The count was reduced into negatives
```
<img width="1000" alt="Screenshot 2022-11-20 at 12 03 40 PM" src="https://user-images.githubusercontent.com/2439146/202915386-bafa0338-64fc-4c86-b8b6-5612d7040c57.png">

The weird part is that image above happens intermittently

**Comment by patchthecode** [comment]
using version 2.1.3

**Comment by patchthecode** [comment]
<img width="1110" alt="Screenshot 2022-11-20 at 12 07 10 PM" src="https://user-images.githubusercontent.com/2439146/202915562-951b9be6-a3c6-4e5c-92a1-a02205c3dbe3.png">

another intermittent error

**Comment by patchthecode** [comment]
IkigaJSON/JSONDescription.swift:121: Fatal error: The JSON index is corrupt. No JSON Type could be found at offset 17. Please file a bug report on Github.

<img width="1101" alt="Screenshot 2022-11-20 at 12 10 16 PM" src="https://user-images.githubusercontent.com/2439146/202915713-0aca6679-76c9-40f5-bccf-41fb4cfcc23e.png">

**Comment by Joannis** [comment]
For anyone reading this; I can't reproduce this yet using the code & JSON provided. If you ever run into this or a similar issue, please submit your JSON if possible, or modify it to hide data while still crashing the parser.

**Comment by patchthecode** [comment]
fixed when i updated to 2.1.4
